### PR TITLE
Повеликин Ростислав - лабораторная работа #0

### PR DESCRIPTION
**Pull request by rpovelik**
@might52, @nik709 could you make a review, please? I do not have partners so it's hard for me to find more relevant Java people than you.

Thanks in advance

### CODE REVIEW

**Comment by nik709** [comment]
:+1:

**Comment by might52** [comment]
Reviewed 👍 I don't see any problems.

**Comment by rpovelik** [comment]
@kirill-korniakov

**Comment by rpovelik** [comment]
Closed due to PR from master, not branch

**Pull request closed without merging**
