### PR TITLE
Бевзюк -- Лабораторная работа #0

### PR DESCRIPTION
**Pull request by SemyonBevzuk**
@mkildishev, @KulyginaJulia
Could you review my tests?

### CODE REVIEW

**Comment by mkildishev** [comment]
👍

**Comment by SemyonBevzuk** [comment]
@Nikita-Mitrokhin, could you make a review?

**Comment by Nikita-Mitrokhin** [comment]
:+1:

**Comment by SemyonBevzuk** [comment]
@kirill-korniakov 
Could you check the lab-0?

**Pull request merged**
