### PR TITLE
Кильдишев Максим - Лабораторная работа #0

### PR DESCRIPTION
**Pull request by mkildishev**
Hi, @SemyonBevzuk and @Nikita-Mitrokhin
Could you please take a look?
If you have a few tests for me, please write it here

### CODE REVIEW

**Comment by SemyonBevzuk** [comment]
👍

**Comment by Nikita-Mitrokhin** [comment]
:+1:

**Comment by mkildishev** [comment]
@kirill-korniakov

**Comment by vgvoleg** [comment]
👍

**Pull request merged**
