### PR TITLE
Зырина -- Лабораторная работа #0

### PR DESCRIPTION
**Pull request by Selllavi**
Зырина Анна - Лабораторная работа #0

### CODE REVIEW

**Comment by Selllavi** [comment]
@ViolettaShirokikh, @Yaroslav-Lahtachev please, review these changes.

**Comment by Yaroslav-Lahtachev** [comment]
Everything looks good 👍

**Comment by ViolettaShirokikh** [comment]
:+1:

**Comment by Selllavi** [comment]
@kirill-korniakov please, have a look on my review :)

**Pull request merged**
