### PR TITLE
Повеликин -- Лабораторная работа #0

### PR DESCRIPTION
**Pull request by rpovelik**

### CODE REVIEW

**Comment by rpovelik** [comment]
Review has already been done by other students in [this PR ](https://github.com/UNN-ITMM-Software/agile-course-practice/pull/6). PR was closed due to incorrect branch

**Comment by rpovelik** [comment]
@allnes

**Comment by rpovelik** [comment]
@Lenferd

**Comment by Lenferd** [comment]
Looks ok to me :+1:

**Comment by allnes** [comment]
:+1:

**Pull request merged**
