### PR TITLE
Шумихин -- Лабораторная работа #3 

### PR DESCRIPTION
**Pull request by Lenferd**

### CODE REVIEW

**Comment by allnes** [comment]
:+1:

**Comment by Lenferd** [comment]
@kirill-korniakov After the exam, it's not so easy to get approval, is it enough?

**Comment by PetrovKP** [comment]
:+1:

**Comment by kirill-korniakov** [comment]
> @kirill-korniakov After the exam, it's not so easy to get approval, is it enough?

После экзамена ревью сокурсников становятся опциональными

**Pull request closed without merging**
