### PR TITLE
Миронова -- Лабораторная работа #3

### PR DESCRIPTION
**Pull request by Anna-Mironova**

### CODE REVIEW

**Comment by Anna-Mironova** [comment]
@SemyonBevzuk , @KulyginaJulia could you review lab3, please?

**Comment by SemyonBevzuk** [comment]
👍

**Comment by KulyginaJulia** [comment]
👍

**Comment by VitKonevskiy** [comment]
Travis - FAIL: copy-paste detected
Please, fix
I suppose you can rename fields to avoid error

**Comment by Anna-Mironova** [comment]
@VitKonevskiy please check

**Pull request merged**
